version: '3'

services:
  animedl:
    init: true
    build:
      context: .
    container_name: animedl
    restart: always
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - ./tmp:/app/tmp
